# Generated by Django 5.0.8 on 2024-08-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='untitled', max_length=200)),
                ('author', models.CharField(default='unknown', max_length=100)),
                ('isbn', models.CharField(max_length=13, null=True, unique=True)),
                ('pages', models.IntegerField(default=2)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('language', models.CharField(default='kannada', max_length=20)),
            ],
        ),
    ]
